repos:
-   repo: local
    hooks:
    -   id: typst-compile
        name: Compile Typst to PDF
        entry: compile_typst.bat
        language: system
        files: \.typ$
        stages: [commit]
